### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by DevNullx64** [Leonardo16AM/Sharp-Grad#1]
Hi :)
I stumbled upon your code a few days ago. I thank you immensely for this little gift to me. I'm an algorithmist, not a mathematician. Formal mathematical language isn't my cup of tea.
I've forked and am nearly finished rewriting almost all of your code. The last time I did this, I upset someone. So, I wanted to make sure that if I submit a pull request, it's not to be mean. And, in case that I don't PR. This is not to steal your work. That's all :)

**Comment by Leonardo16AM** [comment]
Hello, I was pleasantly surprised that my code was useful to you. You can make all the changes you consider or add new things. This week I will be a little busy but after that I can review your PR. Thank you for your collaboration :)
