### ISSUE TITLE
TanH return value

### ISSUE THREAD

**Issue by DevNullx64** [Leonardo16AM/Sharp-Grad#4]
In this:
```
public Value TanH()
{
  Value eThis = Value.e ^ this;
  Value eLa = Value.e ^ -this;
  Value c = (eThis - eLa) / (eThis + eLa);
  Value ret = new Value(c.Data, "tanh", c);
  return c;
}
```

I'm confused because ret not seem to be used. I don't mind side effect that can be usefule in computation. Is the value ret is useless ? or return ret is more interesting (becasue of the namoing of the operation) ?

**Comment by Leonardo16AM** [comment]
Ok, it seems like a bug, i wanted to create a new value, because i wanted the node to have name "tanh",  probably the best is to change c.name to "tanh"

**Comment by Leonardo16AM** [comment]
I fixed it and added TanhValue.cs

**Comment by DevNullx64** [comment]
> Ok, it seems like a bug, i wanted to create a new value, because i wanted the node to have name "tanh", probably the best is to change c.name to "tanh"

It soud like somethink that I suspect. I will mind this "issue". Because, TanH is compute and "autograded" itself. It a use case that should be commmon.
